on: [push, pull_request]

jobs:

  ci-build:
    runs-on: docker
    container:
      image: code.phoswald.ch/philip/builder:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - run: mkdir -p ~/.m2 &&  echo "${{ secrets.M2_SETTINGS }}" > ~/.m2/settings.xml
      - run: mvn -B clean deploy 
